### PR TITLE
Adding support for psr/http-message v.2

### PR DESCRIPTION
**Pull request by MartinLindalHansen**
I ran into this Composer require issue, on a private project of mine (using Laravel 10):

_>  Problem 1
>     - mailersend/mailersend v0.8.0 requires psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
>     - mailersend/laravel-driver v2.2.0 requires mailersend/mailersend ^0.8.0 -> satisfiable by mailersend/mailersend[v0.8.0].
>     - Root composer.json requires mailersend/laravel-driver ^2.2 -> satisfiable by mailersend/laravel-driver[v2.2.0]._

In this pull request, I've updated "psr/http-message" to version ^2.0 
Additionally I've updated "guzzlehttp/psr7" to v.2.5.0  - required to be able to use "psr/http-message" v. 2.0

Ran "composer run test" locally - result: All ok.

Note: 
This is my first ever contribution attempt. 
So please guide me if doing something wrong / missing something.

### CODE REVIEW

**Review by fosron — CHANGES_REQUESTED** [review]
We cant drop support for old versions of said packages.

**Comment by fosron** [comment]
@MartinLindalHansen we can always add `|` symbol to support multiple versions.

**Comment by MartinLindalHansen** [comment]
> @MartinLindalHansen we can always add `|` symbol to support multiple versions.


In my mind I already did that. But then reality didn't agree with me - and I see that now. 
Coming right up 👍

**Comment by fosron** [comment]
@MartinLindalHansen looks good. We will still have to test it so it doesnt break BC

**Comment by MartinLindalHansen** [comment]
> @MartinLindalHansen looks good. We will still have to test it so it doesnt break BC

I need to ask this time:
Running "composer test" fails, if I do not do:

> "composer require --dev php-http/message"

and 

> "composer require --dev php-http/message-factory"

Then everything _(385 tests, 2215 assertions)_ returns **OK**.

What should I do from here - push my code, now with the two new libraries in the composer.json require-dev section?

**Comment by fosron** [comment]
You should not be needing to install specific packages, you should install all them. As you can see our CI runs the tests and they have passed.

**Comment by fosron** [comment]
This has already been fixed in another PR.

**Pull request closed without merging**
